packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@luminescent/ui-qwik@7.0.0-11'
  - '@luminescent/ui@7.0.2'
  - lucide-icons-qwik@1.24.0-qwik-v2

onlyBuiltDependencies:
  - better-sqlite3
  - workerd
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
blockExoticSubdeps: false
