packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAge: 0

onlyBuiltDependencies:
  - better-sqlite3
  - workerd
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
blockExoticSubdeps: false
