export const colors = {
  white: 0xffffff,
  orange: 0xf9801d,
  magenta: 0xc74ebd,
  light_blue: 0x3ab3da,
  yellow: 0xfed83d,
  lime: 0x80c71f,
  pink: 0xf38baa,
  gray: 0x474f52,
  light_gray: 0x9d9d97,
  cyan: 0x169c9c,
  purple: 0x8932b8,
  blue: 0x3c44aa,
  brown: 0x835432,
  green: 0x5e7c16,
  red: 0xb02e26,
  black: 0x1e1b1b,
};

export const patterns = [
  'border',
  'bricks',
  'circle',
  'creeper',
  'cross',
  'curly_border',
  'diagonal_left',
  'diagonal_right',
  'diagonal_up_left',
  'diagonal_up_right',
  'flow',
  'flower',
  'globe',
  'gradient_up',
  'gradient',
  'guster',
  'half_horizontal_bottom',
  'half_horizontal',
  'half_vertical_right',
  'half_vertical',
  'mojang',
  'piglin',
  'rhombus',
  'skull',
  'small_stripes',
  'square_bottom_left',
  'square_bottom_right',
  'straight_cross',
  'stripe_bottom',
  'stripe_center',
  'stripe_downleft',
  'stripe_downright',
  'stripe_left',
  'stripe_middle',
  'stripe_right',
  'stripe_top',
  'triangle_bottom',
  'triangle_top',
  'triangles_bottom',
  'triangles_top',
] as const;