name: Release Please

on:
  push:
    branches:
      - birdflop
    paths:
      - 'packages/rgbirdflop/**'
      - 'packages/analyze/**'
      - 'packages/mc-status/**'
      - '.release-please-manifest.json'
      - 'release-please-config.json'

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout code
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] || steps.release.outputs['packages/analyze--release_created'] || steps.release.outputs['packages/mc-status--release_created'] }}
        uses: actions/checkout@v7

      - name: Setup pnpm
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] || steps.release.outputs['packages/analyze--release_created'] || steps.release.outputs['packages/mc-status--release_created'] }}
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] || steps.release.outputs['packages/analyze--release_created'] || steps.release.outputs['packages/mc-status--release_created'] }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@birdflop'

      # rgbirdflop

      - name: Install dependencies (rgbirdflop)
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] }}
        working-directory: packages/rgbirdflop
        run: pnpm install

      - name: Build package (rgbirdflop)
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] }}
        working-directory: packages/rgbirdflop
        run: pnpm build

      - name: Publish to npm (rgbirdflop)
        if: ${{ steps.release.outputs['packages/rgbirdflop--release_created'] }}
        working-directory: packages/rgbirdflop
        run: npm publish --provenance --access public
        env:
          # it is currently imperative to set NODE_AUTH_TOKEN to an empty string for OIDC auth to work
          # https://github.com/actions/setup-node/blob/633bb92bc0aabcae06e8ea93b85aecddd374c402/src/authutil.ts#L57
          NODE_AUTH_TOKEN: ''

      # analyze

      - name: Install dependencies (analyze)
        if: ${{ steps.release.outputs['packages/analyze--release_created'] }}
        working-directory: packages/analyze
        run: pnpm install

      - name: Build package (analyze)
        if: ${{ steps.release.outputs['packages/analyze--release_created'] }}
        working-directory: packages/analyze
        run: pnpm build

      - name: Publish to npm (analyze)
        if: ${{ steps.release.outputs['packages/analyze--release_created'] }}
        working-directory: packages/analyze
        run: npm publish --provenance --access public
        env:
          # it is currently imperative to set NODE_AUTH_TOKEN to an empty string for OIDC auth to work
          # https://github.com/actions/setup-node/blob/633bb92bc0aabcae06e8ea93b85aecddd374c402/src/authutil.ts#L57
          NODE_AUTH_TOKEN: ''

      # mc-status

      - name: Install dependencies (mc-status)
        if: ${{ steps.release.outputs['packages/mc-status--release_created'] }}
        working-directory: packages/mc-status
        run: pnpm install

      - name: Build package (mc-status)
        if: ${{ steps.release.outputs['packages/mc-status--release_created'] }}
        working-directory: packages/mc-status
        run: pnpm build

      - name: Publish to npm (mc-status)
        if: ${{ steps.release.outputs['packages/mc-status--release_created'] }}
        working-directory: packages/mc-status
        run: npm publish --provenance --access public
        env:
          # it is currently imperative to set NODE_AUTH_TOKEN to an empty string for OIDC auth to work
          # https://github.com/actions/setup-node/blob/633bb92bc0aabcae06e8ea93b85aecddd374c402/src/authutil.ts#L57
          NODE_AUTH_TOKEN: ''
