name: CI Tests

on:
  push:
    branches:
      - birdflop
  pull_request:
    branches:
      - birdflop
  workflow_dispatch:

jobs:
  test:
    name: Lint, Format, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Static Checks
        run: vp check

      - name: Build Library Package
        run: vp run build.pkg

      - name: Run Tests
        run: vp test
